joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_left_wheel_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_right_wheel_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

joint_frw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_wheel_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

joint_flw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_wheel_joint
  pid: {p: 1000.0, i: 0.01, d: 100.0}

joint_blw_position_controller:
  type: position_controllers/JointPositionController
  joint: back_left_motor_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_brw_position_controller:
  type: position_controllers/JointPositionController
  joint: back_right_motor_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_frw_position_controller:
  type: position_controllers/JointPositionController
  joint: front_right_motor_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_flw_position_controller:
  type: position_controllers/JointPositionController
  joint: front_left_motor_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

omni_drive_controller:
  type: omni_drive_controller/OmniDriveController
